# permissions for end users to edit microk8snodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microk8snode-editor-role
rules:
- apiGroups:
  - microk8s.canonical.com
  resources:
  - microk8snodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microk8s.canonical.com
  resources:
  - microk8snodes/status
  verbs:
  - get
