# permissions for end users to view microk8snodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microk8snode-viewer-role
rules:
- apiGroups:
  - microk8s.canonical.com
  resources:
  - microk8snodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microk8s.canonical.com
  resources:
  - microk8snodes/status
  verbs:
  - get
