# permissions for end users to edit nodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-editor-role
rules:
- apiGroups:
  - microk8s.canonical.com
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microk8s.canonical.com
  resources:
  - nodes/status
  verbs:
  - get
