---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - microk8s.canonical.com
  resources:
  - configurations
  - microk8snodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microk8s.canonical.com
  resources:
  - configurations/finalizers
  verbs:
  - update
- apiGroups:
  - microk8s.canonical.com
  resources:
  - configurations/status
  - microk8snodes/status
  verbs:
  - get
  - patch
  - update
