# This configuration will be applied to all cluster nodes
---
apiVersion: microk8s.canonical.com/v1alpha1
kind: Configuration
metadata:
  name: default
spec:
  addonRepositories:
  - name: core
    repository: https://github.com/canonical/microk8s-core-addons
  - name: community
    repository: https://github.com/canonical/microk8s-community-addons
  containerdEnv: |
    ulimit -n 65536 || true
    ulimit -l 16384 || true
  containerdRegistryConfigs:
    docker.io: |
      server = "https://registry-1.docker.io"

      [host."registry-1.docker.io"]
        capabilities = ["pull", "resolve"]
    quay.io: |
      server = "https://quay.io"

      [host."quay.io"]
        capabilities = ["pull", "resolve"]
  extraKubeletArgs:
    max-pods: "200"
  extraKubeAPIServerArgs:
    kubelet-preferred-address-types: "InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP"
  extraSANIPs:
  - 100.100.100.100
  extraSANs:
  - my.kubernetes.cluster
