apiVersion: microk8s.canonical.com/v1alpha1
kind: Configuration
metadata:
  name: default
spec:
  addonRepositories: []
  containerdRegistryConfigs:
    docker.io: |
      server = "http://proxy:5050"
